map $http_upgrade $connection_upgrade {
  default upgrade;
  "" close;
}

server {
  listen 80;

  # 추후 도메인 연결 시 dnkdream.com으로 변경
  server_name localhost;

  # /api 경로 요청 Nest.js 컨테이너로 전달
  location /api/ {
    proxy_pass http://backend:3000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  # 그 외 모든 요청은 Vite SSR 컨테이너로 전달
  location / {
    proxy_pass http://frontend:4000;
    proxy_http_version 1.1;

    # 프론트엔드 핫 리로드 설정
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location /vite-hmr {
    proxy_pass http://frontend:4000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_set_header Host $host;
    proxy_set_header Origin $http_origin;
    proxy_cache_bypass $http_upgrade;
    proxy_buffering off;
  }
}